INSERT INTO USER (COUNTRY, DATE_OF_BIRTH, NAME, NUMBER, PASSWORD, ROLE, ZIP_CODE) VALUES ('India', '1991-02-02', 'admin', 1234567890, 'admin', true, 54321);
INSERT INTO USER (COUNTRY, DATE_OF_BIRTH, NAME, NUMBER, PASSWORD, ROLE, ZIP_CODE) VALUES ('India', '1992-05-04', 'user', 9876543210, 'user', false, 65432);



INSERT INTO PRODUCTS (COMPANY, NAME, TYPES, SIZESDB, PRICE, INFO) VALUES ('Nike', 'AlphaFly','Running', '6_7_8_10', 50, 'The ultra-responsive Nike Air Zoom Tempo NEXT% FlyEase is designed to help you get the most from your training runs, so you can go confidently into your next (or first) race.It has a step-in entry and an internal lacing mechanism you operate with one hand.Pull one loop to tighten, another to release.Colour Shown: Barely Volt/Hyper Orange/Photon Dust/Black');
INSERT INTO PRODUCTS (COMPANY, NAME, TYPES, SIZESDB, PRICE, INFO) VALUES ('Nike', 'Mercurial','Football', '6_7_8_10', 40, 'Embody Kylian Mbappés relentless pace with flames that bring a fast look to your feet.Plus, a stretchy collar creates a seamless fit that moves with you while you blaze past defenders. Colour Shown: Light Thistle/Indigo Burst/Bright Crimson/Metallic Silver');
INSERT INTO PRODUCTS (COMPANY, NAME, TYPES, SIZESDB, PRICE, INFO) VALUES ('Nike', 'KD14','Basketball', '6_7_8_10', 40, 'Kevin Durant lurks on the wing, waiting for the right time to strike before slicing his way through defences.The KD14 is designed to help versatile, relentless players like KD feel fresh all game.Multi-layer mesh and a midfoot strap help reduce your foot movements inside the shoe.Full-length Zoom Air cushioning plus Cushlon foam give back energy for lasting performance.

Colour Shown: Lapis/Turquoise Blue/Light Liquid Lime/Hyper Pink');


INSERT INTO PRODUCTS (COMPANY, NAME, TYPES, SIZESDB, PRICE, INFO) VALUES ('Adidas', 'Adizero','Running', '6_7_8_10', 50, 'The adizero Prime X is created as a boundary-breaking conceptual long distance running shoe. Designed without limitations to amplify key features of the adizero Adios Pro 2 and push the limits of the technology, this shoe also shares the same LIGHTSTRIKE PRO midsole and ENERGYRODS technology and stiffening blades, that spring back added within the heel.');
INSERT INTO PRODUCTS (COMPANY, NAME, TYPES, SIZESDB, PRICE, INFO) VALUES ('Adidas', 'Predator','Football', '6_7_8_10', 40, 'Every time you cross that white line, you enter a whole new world. An alternative reality where you call the shots. The pitch is yours to control. Set your inner freak free in adidas Predator. These football boots have a coated textile upper to help you boss games in comfort. The mid-cut design supports your ankles. A wide expanse of 3D-printed Demonscale elements grip the ball to keep you in charge.');
INSERT INTO PRODUCTS (COMPANY, NAME, TYPES, SIZESDB, PRICE, INFO) VALUES ('Adidas', 'OwnTheGame','Basketball', '6_7_8_10', 40, 'Take control when you step onto the court in these adidas basketball shoes. The mesh upper keeps your feet feeling fresh as you run baseline to baseline. Lightweight cushioning underfoot absorbs impact with every step.');


INSERT INTO PRODUCTS (COMPANY, NAME, TYPES, SIZESDB, PRICE, INFO) VALUES ('Puma', 'Nitro','Running', '6_7_8_10', 50, 'Simply put, the Magnify Nitro Mens Running Shoes give you more of the good stuff. First off theres NITRO FOAM in the midsole - thats PUMAs advanced technology designed to provide amazing responsiveness and cushioning. Then theres PUMAGRIP, a durable rubber compound on the outsole that means you get traction on just about any surface. When comfort is the top priority, but you dont want to sacrifice style, these are the shoes to choose.');
INSERT INTO PRODUCTS (COMPANY, NAME, TYPES, SIZESDB, PRICE, INFO) VALUES ('Puma', 'One','Football', '6_7_8_10', 40, 'The PUMA ONE 19.1 Firm Ground/Artificial Ground Mens Football Boots are offering supreme comfort and fit, promoting speed and facilitating ball control. PUMA’s evoKNIT technology offers a sock-like feel that adapts to your foot, while the FUSEFIT lacing set-up makes for a fit that is tailored to your foot. The RAPIDSPRINT outsole features a stud configuration perfect for speed, while the soft K-Leather upper ensures traction with the ball.');
INSERT INTO PRODUCTS (COMPANY, NAME, TYPES, SIZESDB, PRICE, INFO) VALUES ('Puma', 'Rebirth','Basketball', '6_7_8_10', 40, 'The Disc Rebirth marks the 30th anniversary of the PUMA Disc System. We have grabbed design details from the original and combined it with modern performance technology to bring the disc back on court in a bigger and better way. Rest assured, you will be shooting hoops in pure PUMA style.');